name: Keep Streamlit Apps Awake

on:
  schedule:
    - cron: '0 * * * *'   # every hour
  workflow_dispatch:      # manual trigger

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and run Puppeteer script
        run: |
          docker build -t puppeteer-keep-alive .
          docker run --rm puppeteer-keep-alive
