name: Keep Streamlit Apps Awake

on:
  schedule:
    - cron: '0 * * * *'          # toutes les heures
  workflow_dispatch:             # bouton “Run workflow”

jobs:
  wake-apps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and run script in Docker
        run: |
          docker build -t puppeteer-keep-alive .
          docker run --rm puppeteer-keep-alive
